//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define CMD_TEST_CLEAR                  2
#define IDSAVE                          3
#define CMD_TEST_CLEAR2                 3
#define CMD_TEST_PANGRAM                3
#define IDDEFAULT                       4
#define APP_ICON                        101
#define DLG_MAIN                        103
#define MNU_MAIN                        104
#define ICO_UP                          105
#define ICO_DOWN                        106
#define DLG_ABOUT                       106
#define ICO_RIGHT                       107
#define ICO_LEFT                        108
#define DLG_SAVEOPT                     113
#define DLG_CONFIG                      114
#define DLG_PREVIEW                     115
#define IDB_BITMAP1                     117
#define BFG_LOGO                        117
#define DLG_SPLASH                      119
#define IMG_TEXT                        1000
#define IDC_COMBO1                      1001
#define CBO_FONTS                       1001
#define CBO_CFG_ITEM                    1001
#define IDC_CHECK1                      1002
#define CHK_BOLD                        1002
#define CHK_SAVEOPT_SATURATE            1002
#define IDC_CHECK2                      1003
#define CHK_ITAL                        1003
#define CHK_CFG_WIDTH                   1003
#define CHK_SAVEOPT_INVERT              1003
#define IDC_SPIN1                       1004
#define SPN_FONTHEIGHT                  1004
#define SPN_CFG_CELLWIDTH               1004
#define ID_TEST_BUTTON                  1005
#define IDC_EDIT1                       1005
#define TXT_FONTHEIGHT                  1005
#define TXT_PREVIEW                     1005
#define IDC_SPIN2                       1006
#define SPN_FONTWIDTH                   1006
#define TXT_GREEN                       1006
#define IDC_EDIT2                       1007
#define TXT_FONTWIDTH                   1007
#define TXT_BLUE                        1007
#define IDC_EDIT3                       1008
#define TXT_CELLWIDTH                   1008
#define TXT_CFG_CELLWIDTH               1008
#define IDC_EDIT4                       1009
#define TXT_CELLHEIGHT                  1009
#define TXT_CFG_CELLHEIGHT              1009
#define IDC_COMBO2                      1010
#define CBO_ALIAS                       1010
#define TXT_CFG_FONTHEIGHT              1010
#define IDC_SPIN3                       1011
#define SPN_CELLWIDTH                   1011
#define TXT_CFG_FONTWIDTH               1011
#define IDC_SPIN4                       1012
#define SPN_CELLHEIGHT                  1012
#define SPN_CFG_CELLHEIGHT              1012
#define SPN_CFG_FONTHEIGHT              1013
#define CBO_IMGXRES                     1013
#define IDC_SCROLLBAR1                  1014
#define SCR_VERT                        1014
#define SPN_CFG_FONTWIDTH               1014
#define CMD_UP                          1015
#define CMD_RIGHT                       1016
#define CMD_DOWN                        1017
#define CMD_LEFT                        1018
#define IDC_SCROLLBAR2                  1019
#define SCR_HOR                         1019
#define CBO_IMGXRES2                    1020
#define CBO_IMGYRES                     1020
#define CBO_ZOOM                        1022
#define CHK_GRID                        1023
#define RAD_ALL                         1024
#define RAD_SEL                         1025
#define IDC_EDIT5                       1026
#define TXT_XADJ                        1026
#define IDC_EDIT6                       1027
#define TXT_YADJ                        1027
#define IDC_RADIO1                      1027
#define CMD_SAVEOPT_8                   1027
#define IDC_RADIO2                      1028
#define TXT_WADJ                        1028
#define CMD_SAVEOPT_24                  1028
#define IDC_RADIO3                      1029
#define ODR_COLOR                       1029
#define TXT_WIDTH                       1029
#define CMD_SAVEOPT_32                  1029
#define CHK_WIDTH                       1030
#define SLD_RED                         1030
#define SLD_GREEN                       1031
#define SLD_BLUE                        1032
#define CBO_CFG_IMGXSIZE                1033
#define SPN_WIDTH                       1034
#define CBO_CFG_IMGYSIZE                1034
#define SPN_START                       1035
#define TXT_START                       1036
#define OWN_MAIN                        1037
#define STA_WIDTH                       1038
#define TXT_RED                         1039
#define CHK_CFG_GRID                    1040
#define ID_OK                           1041
#define CMD_OK                          1042
#define IDC_GL3                         1045
#define IDC_GL                          1045
#define ODR_FORECOL                     1046
#define ODR_BACKCOL                     1047
#define IDC_LIST1                       1049
#define LST_CREDITS                     1049
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_EXIT                    40005
#define ID_FONT_RESET                   40006
#define ID_HELP_ABOUT                   40007
#define ID_VIEW_ZOOMIN                  40008
#define ID_VIEW_ZOOMOUT                 40009
#define ID_VIEW_SHOWGRID                40010
#define ID_FONT_ANTIALIAS               40011
#define ID_ANTIALIAS_NONE               40012
#define ID_ANTIALIAS_NORMAL             40013
#define ID_ANTIALIAS_CLEARTYPE          40014
#define ID_Menu                         40015
#define ID_FILE_EXPORT                  40016
#define ID_EXPORT_TARGA                 40017
#define ID_EXPORT_BITMAP                40018
#define ID_EXPORT_FONTDATA              40019
#define ID_FILE_RESET                   40024
#define ID_FONT_TEST                    40025
#define ID_TOOLS_EXTRACTIMAGE           40027
#define ID_TOOLS_IMPORTIMAGE            40028
#define ID_HELP_CONTENTS                40029
#define ID_TOOLS_CONFIGURATION          40030
#define ID_VIEW_WIDTHMARKERS            40032
#define ID_FILE_SAVEBFF                 40033
#define ID_EXPORT_TARGA32               40034
#define ID_FILE_IMPORT                  40035
#define ID_IMPORT_FONTDATA              40036
#define ID_TOOLS_PREVIEW                40040
#define ID_EXPORT_BIN                   40041
#define ID_SAVE_BFF8                    40042
#define ID_SAVE_BFF24                   40043
#define ID_SAVE_BFF32                   40044
#define ID_HELP_CHECKFORUPDATES         40046
#define ID_FONT_COLOUR                  40047
#define ID_COLOUR_SETTEXTCOLOUR         40048
#define ID_COLOUR_SETBACKGROUNDCOLOUR   40049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
